## Packages setup and etc Part
# roles/system_hardening/tasks/setup.yml

- name: Install required packages - APT
  when: ansible_os_family == "Debian"
  ansible.builtin.import_tasks: packages_apt.yml

# - name: Install required packages - DNF
#   when:
#     - ansible_os_family == "RedHat"
#     - ansible_distribution_major_version | int == 9
#   ansible.builtin.import_tasks: packages_dnf.yml