---
# handlers file for roles/system_hardening
- name: Reload SSH
  ansible.builtin.service:
    name: ssh
    state: reloaded
    enabled: true

- name: Restart Fail2Ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true

- name: Update dynamic MOTD
  ansible.builtin.command: /usr/sbin/update-motd
  changed_when: false
