---
# handlers file for roles/tg_ws_proxy
- name: Restart TG WS Proxy
  become: true
  ansible.builtin.command:
    cmd: |
      docker compose up -d --force-recreate -f /opt/tg-ws-proxy/docker-compose.yml
  changed_when: false
