---
all:
  hosts:
    thunboo_vps_nl:
      ansible_host: vps-nl-1.thunboo.ru
      ansible_port: 2222
      ansible_user: thunboo
      # TODO: Make this config and ansible inside this devcontainer use ssh-agent from host
      ansible_ssh_private_key_file: /workspace/VPS-config/deploy/inventory/user-key
  
  children:
    webservers:
      hosts:
        thunboo_vps_nl:
      vars:
        ansible_become: yes
        ansible_become_method: sudo
        ssh_port: 2222
