#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/system_hardening

# Список необходимых системных пакетов
# -----
# Lists OS packages that must be installed
debian_required_packages:
  - sudo
  - openssh-server
  - ufw
  - fail2ban
  - unattended-upgrades
  - ca-certificates
  - curl
  - vim
