---
# tasks file for roles/system_hardening
# - name: Assert ... config ... is valid
#   ansible.builtin.assert:
#     that:
#       - VAR is defined
#       - VAR in ['VALUE1', 'VALUE2']
#     fail_msg: "Set VAR to VALUE1 or VALUE2"

- name: Break on unsuported operating systems
  when:
    - ansible_os_family != "Debian"
  ansible.builtin.fail:
    msg: Only for Debian family systems

# Work-around for multi-system packages setup
- name: Setup phase
  ansible.builtin.import_tasks: setup.yml

- name: Configure phase
  ansible.builtin.import_tasks: configure.yml
