services:
  tg-ws-proxy:
    container_name: tg-ws-proxy
    image: tg-ws-proxy:latest
    env_file: 
      - path: ./tg-ws-proxy.env
        required: true
    command:
      - --fake-tls-domain
      - thunboo.ru
      #- --proxy-protocol # Not working currently
    ports:
      - "127.0.0.1:8446:8446"
    restart: unless-stopped