---
galaxy_info:
  author: Thunboo
  description: Harden and configure Debian-based VPS hosts
  company: Angara Security
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system
    - security
    - hardening
    - ssh
    - firewall
    - fail2ban
    - nginx

dependencies: []
