---
# Dependency management (download roles/collections)
dependency:
  name: galaxy
  # options:
  #   ignore-certs: false
  #   ignore-errors: false
  #   role-file: requirements.yml
  #   requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: ubuntu_os
    groups:
      - vps
    image: "ubuntu:24.04" # Maybe will need to use a ubuntu+systemd image
    # https://github.com/geerlingguy/docker-ubuntu2404-ansible

    pre_build_image: true # Use already existing image (pull or use pulled one)
    privileged: true
    # command: ["/usr/sbin/init"] # We don't need this for regular ubuntu:24.04 image
    # cgroupns_mode: host # Used for cgroups v2 in newer linux distros for systemd and etc
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:rw
    # tmpfs:
    #   - /run
    #   - /tmp:rw
    env:
      container: docker

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      gathering: smart
      fact_caching: memory
    ssh_connection:
      ssh_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -C -o ControlMaster=auto -o ControlPersist=30m'
  inventory:
    hosts:
      molecule_containers: # It is just a custom name
        children:
          node1:
            hosts:
              ubuntu_os:
                ansible_user: root
                # ansible_ssh_private_key_file: /home/vscode/.ssh/id_ed25519 # Do we need this, if we will use ssh-agent?
    group_vars:
      all:
        ansible_connection: docker
      vps:
        role_creator: thunboo

verifier:
  name: ansible

scenario:
  name: vps_setup
  test_sequence:
    # - cleanup # ? Do we need this?
    # - destroy
    # - syntax # What is this?
    - create
    # - prepare # ? Do we need this for testing this role?
    - converge
    - converge # idempotence
    - verify
    # - cleanup
    - destroy
